# SERVICES TEST
@host = http://localhost:3000/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjg2NjE4NDg0LCJleHAiOjE2ODY3MDQ4ODR9.qi2RGMcW6gbJEA9ypWszqRjt3zdCS0GDH9DS81T7jYY

### Login
POST {{host}}login HTTP/1.1
Content-type: application/json

{
    "usuario": "admin",
    "contrasena": "123456"
}

### INIT DEFAULT
GET {{host}} HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

### FindUsuarios WITH ROLE 'USUARIO'
GET {{host}}usuarios HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

### Creación Carrito WITH ROLE 'USUARIO'
POST {{host}}carrito HTTP/1.1
Content-Type: application/json
x-access-token: {{token}}

{
    "userId": 2,
    "descripcion_carrito": "Carrito3",
    "cursos": [
        {"cursoId":1},
        {"cursoId":2},
        {"cursoId":3}
    ]
}